### ISSUE TITLE
Reproducing ToRA Quoted Results

### ISSUE THREAD

**Issue by emrgnt-cmplxty** [microsoft/ToRA#10]
Hi,

Today I executed the following steps:

- 1. modified infer.sh to point to ToRA code, as shown
`MODEL_NAME_OR_PATH="llm-agents/tora-code-7b-v1.0"`
- 2. Ran  `./scripts/infer.sh`
- 3. Final Eval output was seen as shown below:
```
Num samples: 5000
Num scores: 5000
Timeout samples: 1
Empty samples: 8
Mean score: [29.1]
Type scores: {'Algebra': 41.2, 'Counting & Probability': 22.8, 'Geometry': 14.6, 'Intermediate Algebra': 22.1, 'Number Theory': 30.0, 'Prealgebra': 36.7, 'Precalculus': 19.8}
```

This does not seem to agree with the ~45% quoted in the paper and on the papers with code webpage. Why the large discrepancy, how can I reproduce the quoted numbers?

Edit, here are some relevant environment variables
```bash
>>> torch.__version__
'2.0.1+cu117'
>>> transformers.__version__
'4.35.0'
>>> vllm.__version__
'0.2.1.post1'
```

EDIT:

I think it might just have been the vllm mismatch that drove this difference, as I can replicate the benchmark now after doing pip install -r requirements.txt to sync
```bash
Num samples: 5000
Num scores: 5000
Timeout samples: 2
Empty samples: 1
Mean score: [44.6]
Type scores: {'Algebra': 61.2, 'Counting & Probability': 31.0, 'Geometry': 22.3, 'Intermediate Algebra': 36.2, 'Number Theory': 51.1, 'Prealgebra': 55.5, 'Precalculus': 29.7}
```

**Comment by emrgnt-cmplxty** [comment]
btw, any ideas why the discrepancy occurs?

**Comment by ZubinGou** [comment]
Your analysis makes sense. We also found that vLLM has compatibility issues with different versions of Transformers. Apart from the version provided in the repo, we find that it's also fine to use transformers==4.33.1 and vLLM==0.2.0 for training and inference.
