### ISSUE TITLE
training issues for the model weights

### ISSUE THREAD

**Issue by runzeer** [microsoft/ToRA#12]
Thanks for your excellent work? I noticed that your train scripts employed the "CodeLlama-${MODEL_SIZE}-Python-hf" weights.  I also constructed a small dataset for training but I used your "llm-agents/tora-code-7b-v1.0" model weights to continue finetune on my data.  But when I inference with the finetuned weights. There seems to be wrong and the generated output is "".  So I wonder if the training script should be modified if I wanted to use the tora-code-7b-v1.0 weights. Could you help me? Thanks a lot!

**Comment by ZubinGou** [comment]
Consider checking that the environment is consistent with the requirements.txt?

**Comment by runzeer** [comment]
Thanks for your kindly help. It is because the vllm library cannot support the safetensors file saved by accelerator library. And when will the training data can be released? Thanks a lot!

**Comment by ZubinGou** [comment]
Great to hear you were able to solve the issue! As for the full training data, we're pushing to expedite the release, but I don't have a specific timeline due to the internal review process. Please stay tuned for updates!
