### ISSUE TITLE
Issues installing flash_attention==2.0.1, stuck & also freezes screen on local computer

### ISSUE THREAD

**Issue by cweiqiang** [microsoft/ToRA#14]
Hi thanks for the great work.

I am very keen to explore the work by installing the packages in requirements.txt
but I encountered many problems

pip install 'flash-attn==2.0.1'  and also
MAX_JOBS=4 pip install 'flash-attn==2.0.1' --no-build-isolation

does not work, it keeps getting stuck at "Building wheels for collected packages: flash-attn"

However MAX_JOBS=4 pip install 'flash-attn>=2.0.1' --no-build-isolation works but uses the latest version, may I check if the version for flash-attn 2.3.6 works for the ToRA package usage?

Thanks

**Comment by saravananpsg** [comment]
I do have the similar issue!

I have installed pip install flash-attn==2.0.1without --no-build-isolation. When I try to fine-tune the model, I received the following error message.

  File "/ToRA/src/train/llama2_flash_attn_monkey_patch.py", line 23, in apply_rotary_pos_emb
    1, 1, cos_sin[0].shape[1], cos_sin[0].shape[3]
IndexError: tuple index out of range

**Comment by ZubinGou** [comment]
Hi, flash-attn 2.3.6 is supported with the updated code~
