### ISSUE TITLE
ToRA-Corpus 16k 数据集的格式

### ISSUE THREAD

**Issue by Pobby321** [microsoft/ToRA#2]
请问ToRA-Corpus 16k数据集是什么样的格式
```[tasklist]
### Tasks
```

**Comment by Hosampor** [comment]
> تم تطوير ToRA-Corpus 16k من أجل الحصول على أفضل النتائج
> 
> ### مهام
> بيتا
> [إعطاء ردود الفعل](https://github.com/community/community/discussions/39106)
> لم يتم تعقب أي مهام حتى الآن.
> 1. [ ] 
>                    
>                  
>    
>                  
>                    
>                      
>    
>                    
>                      
>                  
>                
>                
>                  
>      
>        
>          
>        
>    
>      خيارات
>    
>    
>    
>      
>        
>          
>            
>      
>          * تحويل إلى الإصدار
>          * تبديل الإكمال
>          * إعادة تسمية
>          * يزيل
> 2.

**Comment by ZubinGou** [comment]
Here are some [examples](https://github.com/microsoft/ToRA/blob/main/src/prompts/tora/math.md), and please refer to the [ToRA paper](https://arxiv.org/abs/2309.17452) for details.
