### ISSUE TITLE
Could you please provide the results based on more powerful base model llemma_7b?

### ISSUE THREAD

**Issue by ChengpengLi1003** [microsoft/ToRA#20]
Could you please provide the results based on more powerful base model llemma_7b? 
I see the results  "ToRA-Code + DAPT” in the openreview pape, https://openreview.net/forum?id=Ep0TtjVoap, which is 49.5 on MATH. Is that the results fintuned from llemma_7b?

**Comment by ZubinGou** [comment]
Yes, that's finetuned from Llemma-7b with the same ToRA data.
