### ISSUE TITLE
How to create ToRA-format dataset ?

### ISSUE THREAD

**Issue by paprika0741** [microsoft/ToRA#23]
Currently, the ToRA-Corpus 16k dataset is under review by the company and not immediately available. However, our codes are public, enabling you to create your own ToRA-format dataset and train your ToRA models. A 10k dataset should yield decent performance.

_Originally posted by @ZubinGou in https://github.com/microsoft/ToRA/issues/7#issuecomment-1787358039_
 Hello, thank you for your nice code. Could you explain how to create ToRA-format dataset using code in this repo?

**Comment by ZubinGou** [comment]
Please use [this script](https://github.com/microsoft/ToRA/blob/main/src/infer/inference_api.py) for ToRA corpus curation.
