### ISSUE TITLE
How to generate ToRA Corpus based on scripts/infer_api.sh ?

### ISSUE THREAD

**Issue by X-Lai** [microsoft/ToRA#24]
Hi,

Impressive work! 

However, I meet some problems in generating the data. When executing `scripts/infer_api.sh`, I encountered an error thrown from https://github.com/microsoft/ToRA/blob/main/src/infer/inference_api.py#L17. Where is the `api` file? Am I missing anything? Or should I modify the source code to use the official openai API?

Thank you very much! Looking forward to your reply. @ZubinGou

**Comment by ZubinGou** [comment]
Yeah, you should modify the source code to use the official openai API.
