### ISSUE TITLE
Is ToRA-69k, the SFT dataset, open-sourced?

### ISSUE THREAD

**Issue by JianxinMa** [microsoft/ToRA#25]
Hello. I've read your Rho-1 paper and noticed the reference to ToRA-69k, but cannot find a download link. Is the dataset open-source, or have I missed it? Thanks in advance.

**Comment by BowieHsu** [comment]
@JianxinMa nope.

**Comment by ZubinGou** [comment]
Hi, @JianxinMa, I also didn't expect the internal review process to take this long, which has prevented ToRA-Corpus from being compliantly open-sourced. Fortunately, there is now an open-source alternative from Nvidia available:
https://huggingface.co/datasets/nvidia/OpenMathInstruct-1

I hope this helps you!
