### ISSUE TITLE
Thank you for your wonderful work.  Would you share codes for querying GPT4 ? 

### ISSUE THREAD

**Issue by ljch2018** [microsoft/ToRA#3]

**Comment by ZubinGou** [comment]
Absolutely! We will soon clean and upload API inference code for ToRA, which can support any models beyond ToRA, like GPT-4 or ChatGPT. It's very similar to the batch inference code [inference.py](https://github.com/microsoft/ToRA/blob/main/src/infer/inference.py). Furthermore, a demo will be made available in the coming days. Stay tuned!
