### ISSUE TITLE
System Requirements? Is it possible to run the ToRA-Code-34B on a Windows 10 PC with a 3090ti?

### ISSUE THREAD

**Issue by HumanGamer** [microsoft/ToRA#6]
as the title says, Is it possible to run the ToRA-Code-34B on a Windows 10 PC with a 3090ti?

If not, what are the system requirements?

**Comment by ZubinGou** [comment]
You can perform inference with the 34B model with reduced accuracy using GPTQ (https://huggingface.co/TheBloke/tora-code-34b-v1.0-GPTQ) or GGUF (https://huggingface.co/TheBloke/tora-code-34b-v1.0-GGUF).
