### ISSUE TITLE
Will the tora dataset be public?

### ISSUE THREAD

**Issue by AceCHQ** [microsoft/ToRA#7]
Hello, thanks for your excellent job. I want to train ToRA by myself with the code datasets. Will the dataset be public? If it will be public, when can I get it? Thank you again.

**Comment by ZubinGou** [comment]
Currently, the ToRA-Corpus 16k dataset is under review by the company and not immediately available. However, our codes are public, enabling you to create your own ToRA-format dataset and train your ToRA models. A 10k dataset should yield decent performance.
